### ISSUE TITLE
Bulk Edit Milestones

### ISSUE THREAD

**Issue by pet1330** [LCAS/pgr_system#29]
- [ ] Add the ability to bulk delete milestones
- [ ] Add the ability to bulk `shift` milestones by `X` days
- [ ] Round milestones to nearest weekday
